#!/bin/bash

javac -cp .:hamcrest-core-1.3.jar:junit-4.12.jar paxos/*.java

# java -cp .:hamcrest-core-1.3.jar:junit-4.12.jar paxos.Paxos

# run test

java -cp .:hamcrest-core-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore paxos.PaxosTest