#!/bin/bash

javac -cp .:hamcrest-core-1.3.jar:junit-4.12.jar paxos/*.java kvpaxos/*.java

# run test


# # PAXOS TEST
# for i in {1..100}
# do
#      java -cp .:hamcrest-core-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore paxos.PaxosTest
# done



# KV TEST
for i in {1..1}
do
     java -cp .:hamcrest-core-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore kvpaxos.KVPaxosTest
done
